version: "3"

services:
  plants:
    build:
      context: plants
      target: dev
    image: plantdex/plants:dev
    container_name: plants
    env_file:
      - plants/.env
    ports:
      - "4040:4040"
    stdin_open: true
    tty: true

  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - "8080:8080"
      - "9898:9898"
    volumes:
      - ./.traefik:/etc/traefik

  users:
    build:
      context: users
      target: dev
    image: plantdex/users:dev
    container_name: users
    env_file:
      - users/.env
    ports:
      - "4041:4041"
    stdin_open: true
    tty: true

  web:
    build:
      context: web
      target: dev
    image: plantdex/web:dev
    container_name: web
    env_file:
      - web/.env
    ports:
      - "3000:3000"
    volumes:
      - ./web:/web
