version: "3"

services:
  envoy:
    image: envoyproxy/envoy-alpine:v1.18-latest
    container_name: envoy
    environment:
      - ENVOY_UID=777
      - ENVOY_GID=777
    ports:
      - "9901:9901"
      - "10000:10000"
    volumes:
      - ./.envoy:/etc/envoy

  plants:
    build:
      context: plants
      target: dev
    image: plantdex/plants:dev
    container_name: plants
    env_file:
      - plants/.env
    ports:
      - "8081:8080"
    stdin_open: true
    tty: true

  users:
    build:
      context: users
      target: dev
    image: plantdex/users:dev
    container_name: users
    env_file:
      - users/.env
    ports:
      - "8082:8080"
    stdin_open: true
    tty: true

  users-redis:
    image: redis:6-alpine
    container_name: users-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass 1234

  web:
    build:
      context: web
      target: dev
    image: plantdex/web:dev
    container_name: web
    env_file:
      - web/.env
    ports:
      - "8080:8080"
    volumes:
      - ./web:/web
