---
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: ingressroutes.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: IngressRoute
    plural: ingressroutes
    singular: ingressroute
  scope: Namespaced

---
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: traefikservices.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: TraefikService
    plural: traefikservices
    singular: traefikservice
  scope: Namespaced

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-ingress-controller
  namespace: plantdex
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - traefik.containo.us
    resources:
      - ingressroutes
      - traefikservices
    verbs:
      - get
      - list
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-ingress-controller
  namespace: plantdex
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
  - kind: ServiceAccount
    name: traefik-ingress-controller
    namespace: plantdex

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: traefik-ingress-controller
  namespace: plantdex

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik
  namespace: plantdex
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          args:
            - --api.dashboard=true
            - --api.insecure=true
            - --entrypoints.web.address=:9898
            - --providers.kubernetescrd
            - --providers.kubernetesingress
          ports:
            - name: web
              containerPort: 9898
            - name: admin
              containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: traefik
  namespace: plantdex
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - protocol: TCP
      name: web
      port: 9898
      targetPort: 9898
    - protocol: TCP
      name: admin
      port: 8080
      targetPort: 8080

---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: plants
  namespace: plantdex
spec:
  entryPoints:
    - web
  routes:
    - match: "Host(`plants.plantdex.app`) && PathPrefix(`/plants`)"
      kind: Rule
      services:
        - name: plants-service
          port: 4040
    - match: "Host(`users.plantdex.app`) && PathPrefix(`/users`)"
      kind: Rule
      services:
        - name: users-service
          port: 4041
    - match: "Host(`plantdex.app`) && PathPrefix(`/`)"
      kind: Rule
      services:
        - name: web-service
          port: 3000
