kind: HTTPProxy
apiVersion: projectcontour.io/v1
metadata:
  name: plants
  namespace: plantdex
spec:
  virtualhost:
    fqdn: plants.plantdex.app
    corsPolicy:
      allowCredentials: true
      allowOrigin:
        - https://plantdex.app
      allowMethods:
        - DELETE
        - GET
        - OPTIONS
        - POST
        - PUT
      allowHeaders:
        - accept
        - authorization
        - content-type
        - origin
      maxAge: "24h"
    tls:
      secretName: tls-secret
  routes:
    - conditions:
        - prefix: /plants
      services:
        - name: plants-service
          port: 4040

---
kind: HTTPProxy
apiVersion: projectcontour.io/v1
metadata:
  name: users
  namespace: plantdex
spec:
  virtualhost:
    fqdn: users.plantdex.app
    corsPolicy:
      allowCredentials: true
      allowOrigin:
        - https://plantdex.app
      allowMethods:
        - GET
        - OPTIONS
        - POST
      allowHeaders:
        - accept
        - authorization
        - content-type
        - origin
      maxAge: "24h"
    tls:
      secretName: tls-secret
  routes:
    - conditions:
        - prefix: /users
      services:
        - name: users-service
          port: 4041

---
kind: HTTPProxy
apiVersion: projectcontour.io/v1
metadata:
  name: web
  namespace: plantdex
spec:
  virtualhost:
    fqdn: plantdex.app
    tls:
      secretName: tls-secret
  routes:
    - conditions:
        - prefix: /
      services:
        - name: web-service
          port: 3000
      responseHeadersPolicy:
        set:
          - name: Content-Security-Policy
            value: "default-src 'self' *.plantdex.app; style-src 'unsafe-inline'"
          - name: Referrer-Policy
            value: "strict-origin-when-cross-origin"
          - name: Strict-Transport-Security
            value: "max-age=63072000; includeSubDomains; preload"
          - name: X-Content-Type-Options
            value: "nosniff"
          - name: X-Frame-Options
            value: "SAMEORIGIN"
          - name: X-XSS-Protection
            value: "1; mode=block"
