apiVersion: getambassador.io/v2
kind: Module
metadata:
  name: ambassador
  namespace: ambassador
spec:
  config:
    defaults:
      httpmapping:
        add_response_headers:
          via: "Ambassador"

---
kind: Mapping
apiVersion: getambassador.io/v2
metadata:
  name: plants
  namespace: ambassador
spec:
  prefix: /plants/
  service: plants-service.plantdex:4040
  add_response_headers:
    Access-Control-Allow-Credentials: true,
    Access-Control-Allowed-Headers: "Accept, Authorization, Content-Type, Origin"
    Access-Control-Allowed-Methods: "GET, OPTIONS, POST"
    Access-Control-Allowed-Origins: "https://plantdex.app"
    Access-Control-Max-Age: 86400,
    Strict-Transport-Security: "max-age=63072000; includeSubDomains; preload"

---
kind: Mapping
apiVersion: getambassador.io/v2
metadata:
  name: users
  namespace: ambassador
spec:
  prefix: /users/
  service: users-service.plantdex:4041
  add_response_headers:
    Access-Control-Allow-Credentials: true,
    Access-Control-Allowed-Headers: "Accept, Authorization, Content-Type, Origin"
    Access-Control-Allowed-Methods: "GET, OPTIONS, POST"
    Access-Control-Allowed-Origins: "https://plantdex.app"
    Access-Control-Max-Age: 86400,
    Strict-Transport-Security: "max-age=63072000; includeSubDomains; preload"

---
kind: Mapping
apiVersion: getambassador.io/v2
metadata:
  name: web
  namespace: ambassador
spec:
  prefix: /
  service: web-service.plantdex:3000
  add_response_headers:
    Content-Security-Policy: "default-src 'self' *.plantdex.app; style-src 'unsafe-inline'"
    Referrer-Policy: "strict-origin-when-cross-origin"
    Strict-Transport-Security: "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options: "nosniff"
    X-Frame-Options: "SAMEORIGIN"
    X-XSS-Protection: "1; mode=block"
