kind: Deployment
apiVersion: apps/v1
metadata:
  name: plants-deployment
  namespace: plantdex
spec:
  selector:
    matchLabels:
      app: plants
  template:
    metadata:
      labels:
        app: plants
    spec:
      containers:
        - name: plants
          image: eu.gcr.io/plantdex-prod/plants:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: plants-configmap
            - secretRef:
                name: plants-secret
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "200Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: plants-service
  namespace: plantdex
spec:
  selector:
    app: plants
  ports:
    - port: 80
      targetPort: 8080
