kind: Deployment
apiVersion: apps/v1
metadata:
  name: plants-deployment
  namespace: plantdex
  labels:
    app: plants
spec:
  selector:
    matchLabels:
      app: plants
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: plants
    spec:
      containers:
        - name: plants
          image: plantdex/plants:prod
          imagePullPolicy: Never
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - containerPort: 4040
          envFrom:
            - configMapRef:
                name: plants-configmap
            - secretRef:
                name: plants-secret

---
kind: Service
apiVersion: v1
metadata:
  name: plants-service
  namespace: plantdex
spec:
  selector:
    app: plants
  ports:
    - protocol: TCP
      port: 4040
      targetPort: 4040
