kind: Deployment
apiVersion: apps/v1
metadata:
  name: users-deployment
  namespace: plantdex
spec:
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: eu.gcr.io/plantdex-prod/users
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "200Mi"
              cpu: "100m"
          ports:
            - containerPort: 4041
          envFrom:
            - configMapRef:
                name: users-configmap
            - secretRef:
                name: users-secret
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4041
          readinessProbe:
            httpGet:
              path: /readyz
              port: 4041

---
kind: Service
apiVersion: v1
metadata:
  name: users-service
  namespace: plantdex
spec:
  selector:
    app: users
  ports:
    - port: 80
      targetPort: 4041
