kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-deployment
  namespace: plantdex
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: eu.gcr.io/plantdex-prod/web
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "200Mi"
              cpu: "100m"
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: web-configmap

---
kind: Service
apiVersion: v1
metadata:
  name: web-service
  namespace: plantdex
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
