name: Deploy web app

on:
  push:
    branches: [main]
    paths:
      - "web/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: web

env:
  APP_NAME: web
  REGISTRY: eu.gcr.io

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud
        uses: google-github-actions/setup-gcloud@master
        with:
          export_default_credentials: true
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Add environment variables
        run: |
          echo "PLANTS_URL=${{ secrets.PLANTS_URL }}" >> .env
          echo "USERS_URL=${{ secrets.USERS_URL }}" >> .env

      - name: Get git sha
        run: echo "GIT_SHA=`echo $(git rev-parse --short HEAD)`" >> $GITHUB_ENV

      - name: Build image
        run: |
          docker build \
          -t "$REGISTRY"/"${{ secrets.GCP_PROJECT_ID }}"/"$APP_NAME":"$GIT_SHA" \
          --target=prod \
          ./

      - name: Push image
        run: docker push "$REGISTRY"/"${{ secrets.GCP_PROJECT_ID }}"/"$APP_NAME":"$GIT_SHA"

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get git sha
        run: echo "GIT_SHA=`echo $(git rev-parse --short HEAD)`" >> $GITHUB_ENV

      - name: Update image tag
        run: sed -i "s/:latest/:$GIT_SHA/i" ../.kubernetes/web.yaml

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: "${{ secrets.DO_ACCESS_TOKEN }}"

      - name: Set up DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save "$CLUSTER_NAME"
        env:
          CLUSTER_NAME: "${{ secrets.CLUSTER_NAME }}"

      - name: Deploy to Kubernetes
        run: kubectl apply -f ../.kubernetes/web.yaml
